# The configuration file is a yaml file that follows yaml format
#
# The directory to your dataset
# The data must be organized as /path/to/dataset/your_video_name/src/%010d.png, start from id=0
# We use png to avoid error caused by jpeg compression
data_dir: ../dataset
#
# Set the default value of parameters here
# All the parameters here will be forwarded to each instance
# You can add any variables here as long as you obey the basic yaml format.
# So please use this part nicely to avoid hard-coding.
# You could specify multiple values for each parameter through yaml list. The code will automatically sweep all parameters for you
default:
  # overwrite existing results or not
  overwrite: False
  # the video name you want to run. Can be a list or a single string
  video_name: trafficcam_1
  # if use host
  hname: False
  # resolution is a number in (0, 1]. We will scale the width and the hight according to this factor
  resolution: -1
  # quantization parameter, higher qp means worse quality
  qp: -1
  # if estimate bandwidth
  estimate_bandwidth: False
  # The path to the ground truth. Will be automatically set in entrance.py
  ground_truth: False
  # mode can be emulation or implementation. Emulation: trasmit the video through disk, Implementation: send the video through http protocol
  mode: emulation
#
# Specify each instance here
# You could overwrite the default configuration for each instance
# The configuration will be directly forwarded to the server
# You could specify multiple values for each parameter through yaml list
# We will automatically spawn multiple instances for you
# E.g., if you specify qp = [1,2], resolution = [0.6,0.8]
# You will get four instances with (qp,resolution)=(1,0.6),(1,0.8),(2,0.6),(2,0.8)
instances:
- method: gt
  qp: 24
  resolution: 1.0
- method: dds
  qp: 26
  resolution: 0.8
